[application]
host = "127.0.0.1"
base_url = "http://127.0.0.1"

[database]
require_ssl = false
host = "localhost"

[email_client]
base_url = "https://api.postmarkerapp.com"
sender_email = "caiyuanrui@sjtu.edu.cn"
